/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package login_panels;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;
/**
 *
 * @author Gelo
 */
public class NewPassword extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(NewPassword.class.getName());
     private String email; // email of the user whose password will be changed

    /**
     * Creates new form NewPassword
     */
    public NewPassword(String email) {
         this.setUndecorated(true);
        initComponents();
        this.email = email;
    }
    public NewPassword() {
    this.setUndecorated(true);
    initComponents();
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnConfirmChange = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        edtNewPassword = new javax.swing.JPasswordField();
        edtConfirmPassword = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(245, 245, 245));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 1, 38)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(65, 105, 225));
        jLabel3.setText("New Credentials");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, 380, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel5.setText("New Password");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 350, 150, -1));

        btnConfirmChange.setBackground(new java.awt.Color(65, 105, 225));
        btnConfirmChange.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnConfirmChange.setForeground(new java.awt.Color(255, 255, 255));
        btnConfirmChange.setText("Confim Change");
        btnConfirmChange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                REDACTED(evt);
            }
        });
        jPanel2.add(btnConfirmChange, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 570, 300, 40));

        jButton2.setBackground(new java.awt.Color(245, 245, 245));
        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jButton2.setText("X");
        jButton2.setBorder(null);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 0, 50, 30));

        edtNewPassword.setBackground(new java.awt.Color(245, 245, 245));
        edtNewPassword.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        edtNewPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtNewPasswordActionPerformed(evt);
            }
        });
        jPanel2.add(edtNewPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 380, 290, 40));

        edtConfirmPassword.setBackground(new java.awt.Color(245, 245, 245));
        edtConfirmPassword.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        edtConfirmPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                REDACTED(evt);
            }
        });
        jPanel2.add(edtConfirmPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 490, 290, 40));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel7.setText("Confirm Password");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 460, 150, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login_panels/rehabilitation.png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, -1, 240));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 473, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 712, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void REDACTED(java.awt.event.ActionEvent evt) {//GEN-FIRST:REDACTED
        
        
         String newPass = new String(edtNewPassword.getPassword());
    String confirmPass = new String(edtConfirmPassword.getPassword());

    if (newPass.isEmpty() || confirmPass.isEmpty()) {
        Toast.error(this, "Please fill in both fields.");
        return;
    }

    if (!newPass.equals(confirmPass)) {
        Toast.warning(this, "Passwords do not match!");
        return;
    }

    try {
        Class.forName("com.mysql.cj.jdbc.Driver");
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/java_users_db", "root", "");

        PreparedStatement pst = con.prepareStatement("UPDATE users SET password=? WHERE email=?");
        pst.setString(1, newPass);
        pst.setString(2, email);
        int rows = pst.executeUpdate();

        if (rows > 0) {
            Toast.success(this, "Password successfully updated!");
            LoginPage login = new LoginPage();
            login.setVisible(true);
            login.setLocationRelativeTo(null);
            dispose();
        } else {
            Toast.warning(this, "Failed to update password!");
        }

        pst.close();
        con.close();
    } catch (Exception e) {
        Toast.error(this, "Error: " + e.getMessage());
    }
        

    }//GEN-LAST:REDACTED

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void edtNewPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:REDACTED
        // TODO add your handling code here:
    }//GEN-LAST:REDACTED

    private void REDACTED(java.awt.event.ActionEvent evt) {//GEN-FIRST:REDACTED
        // TODO add your handling code here:
    }//GEN-LAST:REDACTED

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.REDACTED ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new NewPassword().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfirmChange;
    private javax.swing.JPasswordField edtConfirmPassword;
    private javax.swing.JPasswordField edtNewPassword;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}

